// vue/todolist/todo-app/src/components/InputArea.vue
<template>
  <div class="textarea">
    <input
      type="text"
      class="textbox"
      placeholder="Enter your thoughts···"
      v-model="inputText"
      @keyup.enter="addTask"
      @input="updateButtonState"
    />
    <button
      class="addbtn"
      :class="{ active: inputText.length > 0 }"
      @click="addTask"
    >
      +
    </button>
  </div>
</template>

<script setup lang="ts">
import { ref } from "vue";
const inputText = ref("");

const emit = defineEmits<{
  (e: "add-task", taskText: string): void;
}>();
const addTask = () => {
  if (inputText.value.length > 0) {
    emit("add-task", inputText.value);
    inputText.value = "";
  }
};
const updateButtonState = () => {};
</script>

// todoapp-react/my-todo/src/components/InputArea.tsx
import { useState } from "react";

interface Props {
  addTodo: (text: string) => void;
}

function InputArea({ addTodo }: Props) {
  const [value, setvalue] = useState<string>("");

  //value.trim()把字符串前后空格去掉
  const handleAdd = () => {
    if (!value.trim()) return;
    addTodo(value.trim());
    setvalue("");
  };

  return (
    <div className="input-area">
      <input
        type="text"
        placeholder="Enter your thoughts..."
        value={value}
        onChange={(e) => setvalue(e.target.value)}
      />
      <button className="add-btn" onClick={handleAdd}>
        +
      </button>
    </div>
  );
}
export default InputArea;
