// vue/todolist/todo-app/src/components/StatusBar.vue
<template>
  <div class="status-bar">
    <div class="tasks-left">
      <span class="pending-count">{{ pendingCount }}</span
      >tasks left
    </div>
    <button
      class="clear-all"
      @click="emit('clear-all')"
      :disabled="pendingCount === 0"
    >
      Clear All
    </button>
  </div>
</template>

<script setup lang="ts">
defineProps<{
  pendingCount: number;
  totalCount: number;
}>();

const emit = defineEmits<{
  (e: "clear-all"): void;
}>();
</script>

<style scoped></style>

// todoapp-react/my-todo/src/components/StatusBar.tsx
interface Props {
  clearAll: () => void;
  left: number;
}

function StatusBar({ clearAll, left }: Props) {
  return (
    <div className="status-bar">
      <span className="status-left">
        <span className="count">{left} </span>tasks left
      </span>
      <button onClick={clearAll}>Clear All</button>
    </div>
  );
}
export default StatusBar;
